# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'saltoPopUpApp' do
	pod 'Firebase/Core', '~> 5.6.0'
	pod 'GoogleIDFASupport'
	pod 'Firebase/Messaging', '~> 5.20.1'
end
